version: '3.8'
services:
  app:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"